# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20161010_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='month',
            field=models.CharField(choices=[('BASE', ''), ('TWO_COLUMN', 'two_column'), ('THREE_COLUMN', 'three_column'), ('HERO', 'hero')], default='BASE', max_length=20),
        ),
    ]
