# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaign_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='month',
            new_name='template',
        ),
    ]
