# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20161010_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.CharField(choices=[('', 'generic'), ('TWO_COLUMN', 'two column'), ('THREE_COLUMN', 'three column'), ('HERO', 'hero')], default='', max_length=20),
        ),
    ]
