# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20161010_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.CharField(blank=True, choices=[('generic', 'generic'), ('two_column', 'two column'), ('three_column', 'three column'), ('hero', 'hero')], default='generic', max_length=20, null=True),
        ),
    ]
