# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20161010_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sidebar',
            new_name='LeftSidebar',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='sidebar',
            new_name='left_sidebar',
        ),
        migrations.AddField(
            model_name='campaign',
            name='right_sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.RightSidebar'),
        ),
    ]
